//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 12 2013 11:45:38).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

@interface CMessageWrap : NSObject
{

}

@property(nonatomic) unsigned long m_uiMessageType; // @synthesize m_uiMessageType;
@property(nonatomic) unsigned long m_uiMesLocalID; // @synthesize m_uiMesLocalID;

@end

