//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 12 2013 11:45:38).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

@class CMessageWrap, UIView;

@interface CMessageNodeData : NSObject
{
    int m_eMsgNodeType;
    CMessageWrap *m_msgWrap;
    UIView *m_view;
    unsigned long m_uCreateTime;
}

@property(nonatomic) unsigned long m_uCreateTime; // @synthesize m_uCreateTime;
@property(retain, nonatomic) UIView *m_view; // @synthesize m_view;
@property(retain, nonatomic) CMessageWrap *m_msgWrap; // @synthesize m_msgWrap;
@property(nonatomic) int m_eMsgNodeType; // @synthesize m_eMsgNodeType;
- (unsigned int)GetNodeViewType;
- (int)compare:(id)arg1;
- (void)dealloc;
- (id)init;

@end

