//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 12 2013 11:45:38).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "MMUIView.h"

@class MMDelegateProxy<WCRedEnvelopesReceiveHomeViewDelegate>, MMWebImageView, NSDictionary, UIButton, UIImageView, UIView;

@interface WCRedEnvelopesReceiveHomeView : MMUIView
{
    MMDelegateProxy<WCRedEnvelopesReceiveHomeViewDelegate> *m_delegate;
    UIImageView *m_backgroundView;
    UIButton *openRedEnvelopesButton;
    UIImageView *openAnimationImageView;
    struct CGRect m_frame;
    NSDictionary *m_dicBaseInfo;
    BOOL m_bSuccessAnmation;
    UIView *oRedView;
    UIView *oTopHeaderView;
    MMWebImageView *imageView;
    MMWebImageView *maskImageView;
}

- (id).cxx_construct;
- (void)showSuccessOpenAnimation;
- (void)removeView;
- (void)endAnimation;
- (void)showAnimation;
- (void)stopReceiveAnimation;
- (void)startReceiveAnimation;
- (void)OnOpenRedEnvelopes;
- (void)OnOpenList;
- (void)OnCancelButtonDone;
- (id)initWithFrame:(struct CGRect)arg1 andData:(id)arg2 delegate:(id)arg3;
- (void)refreshViewWithData:(id)arg1;
- (void)dealloc;

@end

